version: '2'
services:

  postfix:
    build: ./Dockerfiles/docker-postfix
    environment:
      - SERVER_HOSTNAME
      - SMTP_SERVER_IP
      - SMTP_SERVER
      - SMTP_PORT
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - FILTER_SERVER
      - FILTER_SERVER_PORT
      - POSTFIX_DLP_SERVER
      - POSTFIX_DLP_PORT
      - POSTFIX_DLP_HOSTNAME
    ports:
      - 25:25
      - 10026:10026
    expose:
      - 25
    hostname: ${POSTFIX_DLP_HOSTNAME}
    extra_hosts:
      - "${SMTP_SERVER}:${SMTP_SERVER_IP}"
    volumes:
      - PSpoolVolume:/var/spool/postfix
    restart: always
    networks:
      - snet

  postfix-filter:
    build: ./Dockerfiles/parser
    environment:
      - FILTER_SERVER_HOST
      - POSTFIX_DLP_HOSTNAME
      - POSTFIX_DLP_SERVER
    ports: 
      - 10025:10025
    hostname: ${FILTER_SERVER_HOST}
    networks:
      - snet
      - esnet
    volumes:
      - ImagesVolume:/images
      - PFilterVolume:/var/spool/postfix-filter

  images-web:
    build: ./Dockerfiles/images
    ports:
      - 80:80
    hostname: images
    networks:
      - snet
    volumes_from:
      - postfix-filter

  tika-parser:
    build: ./Dockerfiles/tika
    ports:
      - 9998:9998
    hostname: tika
    networks:
      - snet

  elasticsearch:
    build: ./Dockerfiles/elasticsearch
    ports:
      - 9200:9200
    hostname: elasticsearch
    networks:
      - esnet
      - snet
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2048m
    volumes:
      - ESDataVolume:/usr/share/elasticsearch/data
      - ./Dockerfiles/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    build: ./Dockerfiles/kibana
    ports:
      - 5601:5601
    hostname: kibana
    depends_on:
      - elasticsearch
    networks:
      - snet
    volumes:
      - ./Dockerfiles/kibana/config/:/usr/share/kibana/config

  image-parser:
    image: buildpack-deps:stretch
    build: ./Dockerfiles/ocr
    networks:
      - snet
volumes:
  PSpoolVolume:
  PFilterVolume:
  ESDataVolume:
  ImagesVolume:
networks:
  snet:
  esnet:
