version: '2'
services:
  emailrelay-in:
    build: ./Dockerfiles/emailrelay-in
    ports:
      - 587:587
    expose:
      - 587
    hostname: emailrelay-in
    volumes:
      - ERSpoolVolume:/var/spool/emailrelay
    depends_on:
      - emailrelay-out
    networks:
      - ernet

  emailrelay-out:
    image: pataquets/emailrelay
    ports:
      - ${ER_OUT_PORTNO}
    networks:
      - ernet
    extra_hosts:
      - "${EXT_MAIL_SERVER}:${EXT_MAIL_SERVER_IP}"
    volumes:
      - ERDataVolume:/var/spool/emailrelay
    command:
      - --log 
      - --poll 
      - "0"
      - --forward-to 
      - ${EXT_MAIL_SERVER}:${EXT_MAIL_SERVER_PORT} 
      - --forward
      - --client-tls
      - --tls-config=1
      - --log-time
      - --port
      - "${ER_OUT_PORTNO}"  
      - --filter
      - net:emailrelay-parser:1235 
      - --filter-timeout
      - "70"
      - --remote-clients

  emailrelay-resubmit:
    build: ./Dockerfiles/resubmit
    volumes_from:
      - emailrelay-in
    networks:
      - ernet
 
  emailrelay-parser:
    build: ./Dockerfiles/parser
    ports: 
      - 1235:1235
    hostname: parser
    networks:
      - ernet
      - esnet
    volumes:
      - ImagesVolume:/images
    volumes_from:
      - emailrelay-out

  images-web:
    build: ./Dockerfiles/images
    ports:
      - 80:80
    hostname: images
    networks:
      - ernet
    volumes_from:
      - emailrelay-parser

  tika-parser:
    build: ./Dockerfiles/tika
    ports:
      - 9998:9998
    hostname: tika
    networks:
      - ernet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    ports:
      - 9200:9200
    hostname: elasticsearch
    networks:
      - esnet
      - ernet
    environment:
      - cluster.name=docker-cluster
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap_memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 512m
    volumes:
      - ESDataVolume:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.0
    ports:
      - 5601:5601
    hostname: kibana
    depends_on:
      - elasticsearch
    networks:
      - esnet
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SERVER_NAME=kibana
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme

  image-parser:
    image: buildpack-deps:stretch
    build: ./Dockerfiles/ocr
    networks:
      - ernet
volumes:
  ERSpoolVolume:
  ERDataVolume:
  ESDataVolume:
  ImagesVolume:
networks:
  ernet:
  esnet:
